# to create env from .yml: conda env create -f environment.yml
name: heart
channels:
- conda-forge
dependencies:
- python=3.8.12
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.5.1
- matplotlib=3.4.3
- numpy=1.19.5
- pandas=1.3.2
- scikit-learn=1.0
- seaborn=0.11.2
- python-graphviz==0.19.1
- xgboost=1.4.2
- emoji=1.6.1
- flask=2.0.2
- gunicorn=20.1.0
- pip=21.3.1
- pipenv=2022.1.8 

